/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ITdepartment;

//import ITdepartment.*;
import ITInterface.ScheduleITF;
import ITObject.ScheduleObj;
import java.awt.HeadlessException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author DELL
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form ITdepartment
     */
    DefaultTableModel tableModel;
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    List<ScheduleObj> lst= new ArrayList<>();
    
    public MainMenu() {
        initComponents();
        conn = Connect.connection();
        tableModel = (DefaultTableModel) scheduleTable.getModel();
        //displaySchedule();
        display();
    }

   /* public void displaySchedule(){
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 5000);
            ScheduleITF sc = (ScheduleITF) r.lookup("ScheduleITF");
            lst = sc.displaySchedule();
            tableModel.setRowCount(0);
            for(ScheduleObj sch: lst){
                tableModel.addRow(new Object[]{
                    sch.getClass_id(),
                    sch.getCourse_name(),
                    sch.getSection_id(),
                    sch.getDay_of_week(),
                    sch.getRoom()
                });
            }
        } catch (Exception e) {
        }
    }*/
    
    public void display(){
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 5000);
            ScheduleITF sc = (ScheduleITF) r.lookup("ScheduleITF");
            lst = sc.display();
            tableModel.setRowCount(0);
            for(ScheduleObj sch: lst){
                tableModel.addRow(new Object[]{
                    sch.getClass_id(),
                    sch.getCourse_name(),
                    sch.getSection_id(),
                    sch.getDay_of_week(),
                    sch.getRoom()
                });
            }   
        } catch (Exception e) {
        }
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        searchtxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        scheduleTable = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        editScheduleBtn = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        exit = new javax.swing.JMenu();
        teacherinfo = new javax.swing.JMenuItem();
        course = new javax.swing.JMenuItem();
        section = new javax.swing.JMenuItem();
        ClassView = new javax.swing.JMenuItem();
        exitMenuBtn = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        searchtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        searchtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchtxtKeyReleased(evt);
            }
        });

        scheduleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CLASS ID", "COURSE NAME", "SECTION", "DAY OF WEEK", "ROOM"
            }
        ));
        jScrollPane1.setViewportView(scheduleTable);
        if (scheduleTable.getColumnModel().getColumnCount() > 0) {
            scheduleTable.getColumnModel().getColumn(0).setResizable(false);
            scheduleTable.getColumnModel().getColumn(0).setPreferredWidth(17);
            scheduleTable.getColumnModel().getColumn(2).setResizable(false);
            scheduleTable.getColumnModel().getColumn(2).setPreferredWidth(5);
            scheduleTable.getColumnModel().getColumn(3).setResizable(false);
            scheduleTable.getColumnModel().getColumn(3).setPreferredWidth(100);
            scheduleTable.getColumnModel().getColumn(4).setResizable(false);
            scheduleTable.getColumnModel().getColumn(4).setPreferredWidth(4);
        }

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("SCHEDULE OF IT DEPARTMENT");

        editScheduleBtn.setText("EDIT SCHEDULE");
        editScheduleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editScheduleBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(229, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(292, 292, 292))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editScheduleBtn)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editScheduleBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        exit.setText("MENU");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        teacherinfo.setText("TEACHER INFORMATION");
        teacherinfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherinfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherinfoActionPerformed(evt);
            }
        });
        exit.add(teacherinfo);

        course.setText("VIEW COURSE");
        course.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        course.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseActionPerformed(evt);
            }
        });
        exit.add(course);

        section.setText("VIEW SECTION");
        section.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        section.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sectionActionPerformed(evt);
            }
        });
        exit.add(section);

        ClassView.setText("VIEW CLASS");
        ClassView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ClassView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassViewActionPerformed(evt);
            }
        });
        exit.add(ClassView);

        exitMenuBtn.setText("EXIT");
        exitMenuBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitMenuBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuBtnActionPerformed(evt);
            }
        });
        exit.add(exitMenuBtn);

        jMenuBar1.add(exit);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void exitMenuBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuBtnActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_exitMenuBtnActionPerformed

    private void teacherinfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherinfoActionPerformed
        // TODO add your handling code here:
        Teacher obj = new Teacher();
        obj.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_teacherinfoActionPerformed

    private void courseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseActionPerformed
        // TODO add your handling code here:
        Course obj = new Course();
        obj.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_courseActionPerformed

    private void sectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sectionActionPerformed
        // TODO add your handling code here:
        Section obj = new Section();
        obj.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_sectionActionPerformed

    private void ClassViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassViewActionPerformed
        // TODO add your handling code here:
        
        ViewClass obj = new ViewClass();
        obj.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_ClassViewActionPerformed

    private void editScheduleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editScheduleBtnActionPerformed
        // TODO add your handling code here:
        Schedule obj = new Schedule();
        obj.setVisible(true);
        setVisible(false);
        this.dispose();
    }//GEN-LAST:event_editScheduleBtnActionPerformed

    private void searchtxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchtxtKeyReleased
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel)scheduleTable.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        scheduleTable.setRowSorter(tr);
        tr.setRowFilter(RowFilter.regexFilter(searchtxt.getText().trim()));
    }//GEN-LAST:event_searchtxtKeyReleased
    
     
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClassView;
    private javax.swing.JMenuItem course;
    private javax.swing.JButton editScheduleBtn;
    private javax.swing.JMenu exit;
    private javax.swing.JMenuItem exitMenuBtn;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable scheduleTable;
    private javax.swing.JTextField searchtxt;
    private javax.swing.JMenuItem section;
    private javax.swing.JMenuItem teacherinfo;
    // End of variables declaration//GEN-END:variables
}
