/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package View;

import ComputerShop.PTypeModify;
import ComputerShop.ProductModify;
import ComputerShop.RegisterModify;
import Model.PType;
import Model.Product;
import Model.Register;
import java.rmi.*;
import java.rmi.registry.*;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Xuan040900
 */
public class ViewAllGUI extends javax.swing.JInternalFrame {
    DefaultTableModel tbm1,tbm2,tbm3;
    List<Register> reg = new ArrayList<>();
    List<PType> type = new ArrayList<>();
    List<Product> pro = new ArrayList<>();
    Connection con = null;

    /**
     * Creates new form ViewAll
     */
    public ViewAllGUI() {
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 2000);
            RegisterModify c = (RegisterModify)r.lookup("RegisterModify");
            initComponents();
            tbm1 = (DefaultTableModel) tbProduct.getModel();
            tbm2 = (DefaultTableModel) tbType.getModel();
            tbm3 = (DefaultTableModel) tbUser.getModel();
            showUser();
            showType();
            showProduct();
        } catch (NotBoundException | RemoteException e) {
        }
    }
    
    public void showUser(){
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 2000);
            RegisterModify c = (RegisterModify)r.lookup("RegisterModify");
            reg = c.findAll();
            tbm3.setRowCount(0);
            
            for (Register register : reg) {
                tbm3.addRow(new Object[] {
                    tbm3.getRowCount() + 1, register.getUsername(), register.getEmail(), register.getPassword(), register.getConfirm()
                });
            }
        } catch (NotBoundException | RemoteException e) {
            java.util.logging.Logger.getLogger(UserGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    }
    
    public void showType(){
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 2000);
            PTypeModify c = (PTypeModify)r.lookup("PTypeModify");
            type = c.findAll();
            tbm2.setRowCount(0);
            
            for (PType pType : type) {
                tbm2.addRow(new Object[] {
                    tbm2.getRowCount() + 1, pType.getName()
                });
            }
        } catch (NotBoundException | RemoteException e) {
            java.util.logging.Logger.getLogger(PTypeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    }
    
    public void showProduct(){
        try {
            Registry r = LocateRegistry.getRegistry("localhost", 2000);
            ProductModify c = (ProductModify)r.lookup("ProductModify");
            pro = c.findAll();
            tbm1.setRowCount(0);
            
            pro.forEach(product -> {
                tbm1.addRow(new Object[] {
                    tbm1.getRowCount() + 1, product.getProducer(), product.getPrice(), product.getTypeID()
                });
            });
        } catch (NotBoundException | RemoteException e) {
            java.util.logging.Logger.getLogger(ProductModify.class.getName()).log(java.util.logging.Level.SEVERE, null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbType = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbUser = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("View All");

        tbProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PID", "Producer", "Price", "TypeID"
            }
        ));
        jScrollPane1.setViewportView(tbProduct);

        tbType.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "TID", "Type_name"
            }
        ));
        jScrollPane2.setViewportView(tbType);

        tbUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Username", "Email", "Password", "Confirm"
            }
        ));
        jScrollPane3.setViewportView(tbUser);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Product");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Product_Type");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("User");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbProduct;
    private javax.swing.JTable tbType;
    private javax.swing.JTable tbUser;
    // End of variables declaration//GEN-END:variables
}
