/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignment;

/**
 *
 * @author Xuan040900
 */
public class Exercite extends javax.swing.JFrame {

    /**
     * Creates new form InetAddress
     */
    public Exercite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        Exit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        CheckIP = new javax.swing.JMenuItem();
        SearchIP = new javax.swing.JMenuItem();
        SearchDomain = new javax.swing.JMenuItem();
        SearchIPlocal = new javax.swing.JMenuItem();
        TestIP = new javax.swing.JMenuItem();
        CheckDomain = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("InetAddress");

        jMenu1.setText("Hệ thống");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        jMenu1.add(Exit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Chức năng");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        CheckIP.setText("Kiểm tra loại IP");
        CheckIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckIPActionPerformed(evt);
            }
        });
        jMenu2.add(CheckIP);

        SearchIP.setText("Tìm IP của tên miền");
        SearchIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIPActionPerformed(evt);
            }
        });
        jMenu2.add(SearchIP);

        SearchDomain.setText("Tìm tên miền của IP");
        SearchDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchDomainActionPerformed(evt);
            }
        });
        jMenu2.add(SearchDomain);

        SearchIPlocal.setText("Tìm IP của máy cục bộ");
        SearchIPlocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchIPlocalActionPerformed(evt);
            }
        });
        jMenu2.add(SearchIPlocal);

        TestIP.setText("Kiểm tra IP");
        TestIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TestIPActionPerformed(evt);
            }
        });
        jMenu2.add(TestIP);

        CheckDomain.setText("Kiểm tra 2 tên miền");
        CheckDomain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckDomainActionPerformed(evt);
            }
        });
        jMenu2.add(CheckDomain);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 164, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckIPActionPerformed
        // TODO add your handling code here:
        CheckIP ci = new CheckIP();
//        this.add(ci); dùng để gọi JInternalFrame
        ci.setVisible(true);
    }//GEN-LAST:event_CheckIPActionPerformed

    private void SearchIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIPActionPerformed
        // TODO add your handling code here:
        SearchIP si = new SearchIP();
//        this.add(si);
        si.setVisible(true);
    }//GEN-LAST:event_SearchIPActionPerformed

    private void SearchDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchDomainActionPerformed
        // TODO add your handling code here:
        SearchDomain sd = new SearchDomain();
//        this.add(sd);
        sd.setVisible(true);
    }//GEN-LAST:event_SearchDomainActionPerformed

    private void SearchIPlocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchIPlocalActionPerformed
        // TODO add your handling code here:
        SearchIPlocal si = new SearchIPlocal();
//        this.add(si);
        si.setVisible(true);
    }//GEN-LAST:event_SearchIPlocalActionPerformed

    private void TestIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TestIPActionPerformed
        // TODO add your handling code here:
        TestIP ti = new TestIP();
//        this.add(ti);
        ti.setVisible(true);
    }//GEN-LAST:event_TestIPActionPerformed

    private void CheckDomainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckDomainActionPerformed
        // TODO add your handling code here:
        CheckDomain cd = new CheckDomain();
//        this.add(cd);
        cd.setVisible(true);
    }//GEN-LAST:event_CheckDomainActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercite.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Exercite().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem CheckDomain;
    private javax.swing.JMenuItem CheckIP;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenuItem SearchDomain;
    private javax.swing.JMenuItem SearchIP;
    private javax.swing.JMenuItem SearchIPlocal;
    private javax.swing.JMenuItem TestIP;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
